### ISSUE TITLE
Check if docker is started on host machine, and if not, start it

### ISSUE THREAD

**Issue by LeeZeitz** [Fattouche/Stratocumulus#15]

**Comment by gurjy0t** [comment]
Do we want to do this in the CLI on first use? Regardless of the command?

Are we trying to do this through python or just run a script? I have a shell script working for Mac but jw what windows we need to support? 10 only im guessing?

**Comment by Fattouche** [comment]
So after reading some stuff about mac, windows and linux I see 2 main problems.

1. There is no real way to start the daemon in windows unless we try to find the executable.
2. Even if we can successfully start it on these operating systems, it takes several seconds to boot up which means we will have to wait for the daemon to start before continuing any other commands. 

My solution(temporary if you want to implement this feature fully) is to just notify them in a clean manner if their daemon is not running.
