### ISSUE TITLE
Need cumulus stop and cumulus kill

### ISSUE THREAD

**Issue by CailanStm** [Fattouche/Stratocumulus#29]
Right now, cumulus stop performs a `docker-compose down`, which means every time you do `cumulus start`, you'll have to wait for the containers to completely re-initialize, which takes a while (over a minute for mysql, for example)

Instead, we should have `cumulus kill` to do what's described above, and then `cumulus stop` which just runs `docker-compose stop`, so that starting up after is fast

This will leave containers around (until `cumulus kill` is performed), but is worth it for the performance boost

**Comment by Fattouche** [comment]
Fixed
